name: ial_wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.20.0
  firebase_auth: 3.4.2
  cloud_firestore: 3.4.3
  firebase_storage: 10.3.4
  convex_bottom_bar: 3.0.0
  shared_preferences: 2.0.15
  image_picker: 0.8.5
  path_provider: 2.0.11
  google_fonts: 3.0.1
  intl: 0.17.0
  week_of_year: 2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/img/
