// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZOc6fyo0MeZgXTkiyR4e1AYS-vjtfvgo',
    appId: '1:1013048315651:android:cce73532b9e441b4676336',
    messagingSenderId: '1013048315651',
    projectId: 'ial-wallet-ae502',
    storageBucket: 'ial-wallet-ae502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOPmI6bXYcITX147m-zciM5LRQ2mt7Svw',
    appId: '1:1013048315651:ios:8dd20a5a1379f6a6676336',
    messagingSenderId: '1013048315651',
    projectId: 'ial-wallet-ae502',
    storageBucket: 'ial-wallet-ae502.appspot.com',
    androidClientId: '1013048315651-pjsemd6jqf7h7q0iov8q33usnm0m1vfv.apps.googleusercontent.com',
    iosClientId: '1013048315651-931u1l4nkj5ha2osg6t3mb3abdb9qsed.apps.googleusercontent.com',
    iosBundleId: 'com.example.ialWallet',
  );
}
